### ISSUE TITLE
대량 email 등록에서 에디터 컴포넌트 로드가 안 되는 문제

### ISSUE THREAD

**Issue by cydemo** [ForPeople/WooriAlim#11]
대량 email 등록에서 에디터 컴포넌트가 로드가 안 돼서
tpl/mailing.html 101행

>  $option->enable_component = false;
를
>  $option->enable_component = true;
로 바꿔주니 로드가 되었습니다.

또한 (마이너하긴 하지만) 라이믹스 debug에서 "Warning: Creating default object from empty value"라는 에러가 떠서 
tpl/mailing.html 97행에

> $option = new stdClass();
를 붙여주니 에러가 뜨지 않게 됐습니다.

**Comment by ForPeople** [comment]
수정되었습니다.
감사합니다.

https://github.com/ForPeople/WooriAlim/commit/443169855e3052d48e9424d2f46fe354c7f454b2
