### ISSUE TITLE
대량 이메일 발송(그룹) 서버오류가 발생합니다.

### ISSUE THREAD

**Issue by wookho** [ForPeople/WooriAlim#12]
https://xetown.com/questions/1426370

PHP Exception: ArgumentCountError #0 "Too few arguments to function ggmailingAdminModel::getGgmailingAdminSendEmail(), 0 passed in /public_html/files/cache/template/modules/ggmailing/tpl/send.html.php on line 96 and exactly 1 expected" in modules/ggmailing/ggmailing.admin.model.php on line 57

**Comment by ForPeople** [comment]
수정되었습니다.
감사합니다.

https://github.com/ForPeople/WooriAlim/commit/443169855e3052d48e9424d2f46fe354c7f454b2
